// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transcodarr.Core.Database;

#nullable disable

namespace Transcodarr.Core.Migrations
{
    [DbContext(typeof(TranscodarrDbContext))]
    partial class TranscodarrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Transcodarr.Core.Database.Entities.AppConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoApplyTranscode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConstantRateFactor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobExpirationInMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TranscodeAudioCodec")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TranscodeEncoderPreset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranscodeTempDirectory")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("TranscodeVideoCodec")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppConfigurations");
                });

            modelBuilder.Entity("Transcodarr.Core.Database.Entities.LibraryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileSystemPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("Transcodarr.Core.Database.Entities.MediaFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FileModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("Status");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("Transcodarr.Core.Database.Entities.MediaFileMetadataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioStreams")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("BitRate")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHdr")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MediaFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoCodec")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId")
                        .IsUnique();

                    b.ToTable("MediaFileMetadataEntity");
                });

            modelBuilder.Entity("Transcodarr.Core.Database.Entities.TranscodeJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AudioCodec")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConstantRateFactor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EncoderPreset")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LeaseExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<double>("Progress")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideoCodec")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("Status", "LeaseExpiresAt");

                    b.ToTable("TranscodeJobs");
                });

            modelBuilder.Entity("Transcodarr.Core.Database.Entities.TranscodeResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ApprovalState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TranscodeJobId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("VmafScore")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TranscodeJobId")
                        .IsUnique();

                    b.ToTable("TranscodeResults");
                });

            modelBuilder.Entity("Transcodarr.Core.Database.Entities.MediaFileEntity", b =>
                {
                    b.HasOne("Transcodarr.Core.Database.Entities.LibraryEntity", "Library")
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Transcodarr.Core.Database.Entities.MediaFileMetadataEntity", b =>
                {
                    b.HasOne("Transcodarr.Core.Database.Entities.MediaFileEntity", "MediaFileEntity")
                        .WithOne("Metadata")
                        .HasForeignKey("Transcodarr.Core.Database.Entities.MediaFileMetadataEntity", "MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFileEntity");
                });

            modelBuilder.Entity("Transcodarr.Core.Database.Entities.TranscodeJobEntity", b =>
                {
                    b.HasOne("Transcodarr.Core.Database.Entities.MediaFileEntity", "MediaFile")
                        .WithMany("Jobs")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("Transcodarr.Core.Database.Entities.TranscodeResultEntity", b =>
                {
                    b.HasOne("Transcodarr.Core.Database.Entities.TranscodeJobEntity", "TranscodeJob")
                        .WithOne("TranscodeResult")
                        .HasForeignKey("Transcodarr.Core.Database.Entities.TranscodeResultEntity", "TranscodeJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TranscodeJob");
                });

            modelBuilder.Entity("Transcodarr.Core.Database.Entities.MediaFileEntity", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("Transcodarr.Core.Database.Entities.TranscodeJobEntity", b =>
                {
                    b.Navigation("TranscodeResult");
                });
#pragma warning restore 612, 618
        }
    }
}
